version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: todo_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "5001:3306" #first-mymachine port last:VM(docker port)
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: